### ISSUE TITLE
idioms-die(3) mentioned twice

### ISSUE THREAD

**Issue by firasuke** [mutinyproject/idioms#1]
I didn't know where to open a pull request for this so I thought I'll open an issue here.

I was reading [theory(5)](https://mutiny.red/theory.5.html#build-idioms) and I stumbled upon this:

> The main functions that you would use from it when writing a package would be idioms-call(3), idioms-error(3), idioms-warn(3), idioms-die(3), and lastly, idioms-die(3).

It seems as if `idioms-die(3)` is mentioned twice, no? Is there a particular reason for that or is it just a typo?

**Comment by somasis** [comment]
Hi! Apologies for the delay, life's been busy and I haven't had much mental energy to devote to projects as of late. I've not yet opened up bug tracking stuff really, this tracker is actually a mistake anyway. My eventual intent is to have a mailing list or something similar in the future when Mutiny is actually a thing people can use.

All that said, thanks for pointing this out, it's indeed a typo.

**Comment by firasuke** [comment]
Glad I could help.

Good luck with your endeavors!
